### ISSUE TITLE
Depth sensor intrinsic parameters missing

### ISSUE THREAD

**Issue by jotaf98** [pammirato/active_vision_dataset_processing#1]
Hi, first of all, thanks for creating this awesome dataset!

I'm trying to put together a point cloud from the depth images and global positions. However, to do this I need the intrinsic parameters of the sensor according to your calibration. Any chance of providing that? Thanks!

**Comment by pammirato** [comment]
they can be found [here](https://drive.google.com/file/d/1mL4DbSpwuuxqN9ZwYachUzbEiFo_v-qc/view?usp=sharing)

**Comment by jotaf98** [comment]
Thanks!
